# Generated by Django 5.1.2 on 2024-10-14 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0002_imageupload"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="uploads/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ImageUpload",
        ),
        migrations.RemoveField(
            model_name="valetkey",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="valetkey",
            name="resource",
        ),
        migrations.AddField(
            model_name="valetkey",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="valetkey",
            name="key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
