# Generated by Django 5.1.2 on 2024-10-19 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_control", "0004_valetkey_can_delete_valetkey_can_edit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="valetkey",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="access_control.resource",
            ),
        ),
    ]
